V10.0 mask
sospartan/weex pull request #105
Opened 2017-01-03 11:08 UTC by xkli

2017-01-03 11:23 UTC, sospartan requested changes

2017-01-03 11:23 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
> +      Shader shader=WXResourceUtils.getShader(bgImage,mDomObj.getLayoutWidth(),mDomObj.getLayoutHeight());
注意代码风格，等号前后空格

2017-01-04 02:36 UTC, sospartan requested changes
对解析部分增加单元测试

2017-01-04 02:36 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/utils/WXResourceUtils.java
> +      case "to right":
这种匹配兼容性太差，如果中间多打了一个空格，就匹配不上了

2017-01-04 02:36 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java
> +        canvas.drawPath(mPathForBorderOutline, mPaint);
这一句可以放到if结构体之后

2017-01-04 02:36 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java
>          mPaint.setShader(null);
使用shader时 这一句可以不用

2017-01-04 02:36 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java
>          canvas.drawPath(mPathForBorderOutline, mPaint);
放到if后，两种绘制方式是一致的

2017-01-05 04:09 UTC, xkli commented on android/sdk/src/main/java/com/taobao/weex/ui/view/border/BorderDrawable.java
> +        canvas.drawPath(mPathForBorderOutline, mPaint);
这句代码必须满足shader==null 或者usecColor 不是透明，不能放到if后

2017-01-05 05:00 UTC, sospartan approved these changes

2017-01-05 05:00 UTC, merged