+ [android] provide ability of default style
sospartan/weex pull request #50
Opened 2016-11-17 06:33 UTC by misakuo

目前提供了以下component的部分默认样式设置能力

名字 | 默认值 |说明|相关组件|
----|------|----|----
backgroud-color | TRANSPARENT  | 背景色| div; image
font-size | 32 (WXText.sDEFAULT_SIZE)  |字体大小| input; textarea; text
color | BLACK |  文本颜色 | input; textarea; text

2016-11-21 06:26 UTC, sospartan requested changes
有点问题，onEmptyProperty只调用了setProperty，如果是通过反射执行的并没有被调用

2016-11-21 06:27 UTC, sospartan requested changes
还有一个问题时，如果这个修改是为了添加默认值，如果props并没有设置这个属性，则默认值不会被设置。

2016-11-22 01:27 UTC, misakuo commented
1. 目前对`onEmptyProperty`的重写只保证实现上面表里所列出的component的默认样式切换，如果要设置其他的默认样式，需要根据需要添加逻辑。
2. 这个修改是为了提供在设置完样式之后恢复默认样式的能力，和jsfm的约定是需要恢复默认样式的属性，会传一个空的属性值回来，我们对空值进行拦截处理

2016-11-22 03:13 UTC, sospartan commented
我的意思是，这个方法一旦添加就等于是我们既定的拓展方式，所以建议能覆盖到反射的部分。可以这样让`onEmptyProperty`返回一个属性值（函数名字可以改下），然后后续的逻辑就可以继续走。

第二个问题我觉得ok，因为现在style也是作为整体传递到native的。

2016-11-22 04:58 UTC, misakuo commented
改了，在property值为空时，调用`convertEmptyProperty`尝试获取默认值

2016-11-22 05:25 UTC, merged