* [android] force hidden keyboard on input destroy
sospartan/weex pull request #61
Opened 2016-12-12 02:59 UTC by misakuo

input component销毁时强制收起键盘

2016-12-12 04:06 UTC, sospartan requested changes

2016-12-12 04:06 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
> +    hideSoftKeyboard();
加一个判断，当前component是否是focus的，否则不相干的component销毁也触发就不对了

2016-12-12 04:58 UTC, misakuo commented on android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
> +    hideSoftKeyboard();
destroy回调到的时候EditText上的焦点已经被清除了，所以没办法判断控件之前是否持有焦点

2016-12-12 05:53 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/ui/component/AbstractEditComponent.java
> +    hideSoftKeyboard();
得想个其他法子，否则就是引入bug了，再想一下

2016-12-13 01:14 UTC, misakuo commented
现在改了逻辑，给HostView加了个OnFocusChangeListener，失去焦点的时候收起键盘

2016-12-13 03:49 UTC, merged

2016-12-13 03:53 UTC, sospartan commented
test case： http://dotwe.org/48491c07237bfd92358e43909d1cb513