* [android] fix slider layout, ignore position offset.
sospartan/weex pull request #71
Opened 2016-12-15 13:37 UTC by sospartan

Slider's is not a regular which apply csslayout top/left/right/bottom to LayoutParameter.

2016-12-15 13:50 UTC, misakuo approved these changes

2016-12-15 13:54 UTC, Rowandjj approved these changes
赞

2016-12-16 03:22 UTC, misakuo requested changes

2016-12-16 03:22 UTC, misakuo commented on android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java
> -        ((ViewGroup.MarginLayoutParams) lp).setMargins(left,top,right,bottom);
不能把margin值都扔掉，需要保证slider item的margin属性依然有效

2016-12-16 04:06 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java
> -        ((ViewGroup.MarginLayoutParams) lp).setMargins(left,top,right,bottom);
除了indicator，普通item的margin可以忽略。已修改。

2016-12-16 04:39 UTC, misakuo approved these changes

2016-12-16 04:39 UTC, merged