add method open in WXNavigatorModule
sospartan/weex pull request #75
Opened 2016-12-19 07:22 UTC by lybeen

@sospartan , please review pr

2016-12-19 10:04 UTC, zshshr commented on android/sdk/src/main/java/com/taobao/weex/appfram/navigator/WXNavigatorModule.java
> +        String url = options.getString("url");
options can be NULL？

2016-12-20 02:03 UTC, sospartan requested changes

2016-12-20 02:03 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/appfram/navigator/WXNavigatorModule.java
> +        String url = options.getString("url");
加一下保护，包括success和failure，那天跟你讨论的时候说过这个。

2016-12-20 02:09 UTC, sospartan commented
@lybeen dear, unittest is broken, fix it.

2016-12-22 03:28 UTC, sospartan approved these changes

2016-12-22 03:50 UTC, merged