* [android] delayed perform transform when component is lazy
sospartan/weex pull request #90
Opened 2016-12-26 09:17 UTC by misakuo

#### bug表现
对懒加载的component应用transform属性无效果
#### 原因
执行`WXAnimationModule.startAnimation`时，懒加载的component还没有创建hostView，导致动画对象被丢弃
#### 解决方案
如果component是lazy的，则先将Animation缓存下来，在hostView创建后再执行动画
#### Testcase
http://dotwe.org/3b5ec98c10a1315d75b1b61d14335cb4

2016-12-28 11:39 UTC, YorkShen requested changes

2016-12-28 11:39 UTC, YorkShen commented on android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationModule.java
> +    }
这里应该可以直接返回吧

2016-12-28 11:39 UTC, YorkShen commented on android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationModule.java
> +    private boolean hasExecuted;
不需要这个字段吧，onHostViewInitialized只应该被执行一次。

2016-12-28 11:39 UTC, YorkShen commented on android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
> +      mAnimationHolder.execute(mInstance, this);
对于覆盖了onHostViewInitialized的component，如[slider](https://github.com/sospartan/weex/blob/b6f2221b53640a479df905b4eb093cce1f2e454c/android/sdk/src/main/java/com/taobao/weex/ui/component/WXSlider.java#L404)，会不会出现做动画的时候，view显示不完整的问题。

2016-12-29 01:23 UTC, misakuo commented on android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
> +      mAnimationHolder.execute(mInstance, this);
所以我加了@CallSuper，如果覆盖了onHostViewInitialized有没有调用super，lint会给一个error

2016-12-29 01:24 UTC, misakuo commented on android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationModule.java
> +    }
可以直接返回的，后面的调用也是直接返回的，这个属于之前的代码没有设计好

2016-12-29 01:24 UTC, misakuo commented on android/sdk/src/main/java/com/taobao/weex/ui/animation/WXAnimationModule.java
> +    private boolean hasExecuted;
如果能确保只会执行一次，那么可以去掉

2016-12-29 03:32 UTC, YorkShen commented on android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
> +      mAnimationHolder.execute(mInstance, this);
我的意思是callsuper是必须的，除此之外，像[indicator](https://github.com/sospartan/weex/blob/b6f2221b53640a479df905b4eb093cce1f2e454c/android/sdk/src/main/java/com/taobao/weex/ui/component/WXIndicator.java#L267)这个组件，在onHostViewInitialized会去更新view树的结构，如果此时先调用动画，view结构后更新，依然会有视觉上的空动画现象。建议加一些注释，让开发人员在写子类的时候，自行决定先调用super. onHostViewInitialized，还是后调用super.onHostViewInitialized

2016-12-29 03:54 UTC, misakuo commented on android/sdk/src/main/java/com/taobao/weex/ui/component/WXComponent.java
> +      mAnimationHolder.execute(mInstance, this);
行，你再看一下，如果描述不清的麻烦补充一下~

2016-12-29 06:56 UTC, YorkShen approved these changes
Great work

2016-12-29 06:57 UTC, merged