Android feature urlconnection interceptor
sospartan/weex pull request #92
Opened 2016-12-27 09:28 UTC by misakuo

默认HttpAdapter实现支持网络访问调试（inspector需要更新以适配该功能，现在暂时移除依赖）

2016-12-28 07:35 UTC, sospartan requested changes
请确保ci通过

2016-12-28 08:51 UTC, misakuo commented
All is well~
![](http://img21.mtime.cn/mg/2011/03/19/111929.14422120.jpg)

2016-12-28 09:48 UTC, sospartan requested changes

2016-12-28 09:48 UTC, sospartan commented on android/playground/app/build.gradle
> +    //compile 'com.taobao.android:weex_inspector:0.8.0.0@aar'
这个依赖没用了么？

2016-12-28 09:48 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/adapter/DefaultWXHttpAdapter.java
> +import com.taobao.weex.urlconnection.WeexURLConnectionManager;
既然是用反射，这里应该去掉吧

2016-12-29 02:46 UTC, misakuo commented on android/playground/app/build.gradle
> +    //compile 'com.taobao.android:weex_inspector:0.8.0.0@aar'
暂时去掉，inspector需要更新，和现在版本的playground代码有冲突，更新后我再补上

2016-12-29 03:17 UTC, sospartan requested changes

2016-12-29 03:17 UTC, sospartan commented on android/sdk/src/main/java/com/taobao/weex/adapter/DefaultWXHttpAdapter.java
> +    return new IEventReporterDelegate() {
每次都new一个新的没必要，弄个static final的field `DEFAULT_DELEGATE`吧

2016-12-29 03:17 UTC, sospartan commented on android/playground/app/build.gradle
> +    //compile 'com.taobao.android:weex_inspector:0.8.0.0@aar'
那等你改完我再merge？还是可以先merge

2016-12-29 03:24 UTC, misakuo commented on android/sdk/src/main/java/com/taobao/weex/adapter/DefaultWXHttpAdapter.java
> +    return new IEventReporterDelegate() {
ok了

2016-12-29 03:25 UTC, misakuo commented on android/playground/app/build.gradle
> +    //compile 'com.taobao.android:weex_inspector:0.8.0.0@aar'
可以先merge，inspector需要依赖sdk的新代码开发功能然后才能更新，那边更新完了我再提一个更新inspector版本的pr

2016-12-30 03:49 UTC, sospartan approved these changes

2016-12-30 03:49 UTC, merged